/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.galois.kotlin-application-conventions")
}

dependencies {
    implementation(project(":core"))
    implementation("info.picocli:picocli:4.6.1")
}

application {
    // Define the main class for the application.
    mainClass.set("org.galois.local.GaloisTerminalKt")
}