/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.galois.kotlin-library-conventions")
    id("org.jetbrains.kotlin.plugin.allopen") version "1.5.20"
    id("org.jetbrains.kotlin.kapt")
}

allOpen {
    annotation("org.openjdk.jmh.annotations.State")
}

dependencies {
    val jmhVersion = "1.32"
    testImplementation("org.openjdk.jmh:jmh-core:$jmhVersion")
    kaptTest("org.openjdk.jmh:jmh-generator-annprocess:$jmhVersion")
}