/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.galois.kotlin-application-conventions")
}

dependencies {
    implementation(project(":core"))
    implementation("io.ktor:ktor-server-netty:1.5.3")
    implementation("io.ktor:ktor-jackson:1.5.3")

}

application {
    // Define the main class for the application.
    mainClass.set("org.galois.web.GaloisUIKt")
}